"""Seeded stochastic disruptions for reproducible sensitivity experiments."""

from __future__ import annotations

import random
from datetime import date

import networkx as nx

from dlm.disruption.schema import Disruption, DisruptionType, Scenario


def random_edge_closure(
    graph: nx.MultiDiGraph,
    *,
    n_edges: int,
    seed: int,
    name: str | None = None,
) -> Scenario:
    """Sample explicit directed edge closures with a stable seed."""

    edges = sorted(graph.edges(keys=True), key=lambda edge: tuple(map(str, edge)))
    if not 1 <= n_edges <= len(edges):
        raise ValueError(f"n_edges must be between 1 and {len(edges)}")
    selected = random.Random(seed).sample(edges, n_edges)
    return Scenario(
        name=name or f"random_edges_{n_edges}_seed_{seed}",
        description=f"Seeded random closure of {n_edges} directed road edges.",
        source="Synthetic scenario generated by dlm.disruption.generators.random_edge_closure.",
        created=date(2026, 8, 16),
        disruptions=(
            Disruption(
                id="random-edges",
                type=DisruptionType.EDGE_CLOSURE,
                edge_ids=tuple(selected),
            ),
        ),
    )
